lumberyard/accounts/urls.py
from django.urls import path

from .views import (
    AccountView,
    LoginView,
    LogoutView,
    PasswordView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    RegisterView,
)


app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('password/', PasswordView.as_view(), name='password'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AccountView.as_view(), name='account'),
]

lumberyard/loglines/urls.py
from django.urls import path

from .views import (
    LoglineCreateView,
    LoglineDetailView,
    LoglineListView,
    LoglineUpdateView,
    LoglineHistoryDetailView
)


app_name = 'loglines'

urlpatterns = [
    path('new/', LoglineCreateView.as_view(), name='logline_create'),
    path('<int:pk>/history/<int:history_pk>/', LoglineHistoryDetailView.as_view(), name='logline_detail_history'),
    path('<int:pk>/update/', LoglineUpdateView.as_view(), name='logline_update'),
    path('<int:pk>/', LoglineDetailView.as_view(), name='logline_detail'),
    path('', LoglineListView.as_view(), name='logline_list'),
]

lumberyard/lumberyard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('loglines/', include('loglines.urls')),
    path('', include('profiles.urls')),
    path('', HomeView.as_view(), name='home'),
]


if getattr(settings, 'DEBUG', False):
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lumberyard/loglines/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from simple_history.models import HistoricalRecords


class Logline(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('loglines:logline_detail', args=[str(self.pk)])

lumberyard/loglines/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .models import Logline
from .utilities import PrettyDiffMatchPatch


class LoglineListView(ListView):
    model = Logline


class LoglineDetailView(DetailView):
    model = Logline


class LoglineCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Logline
    fields = ['title', 'body']
    success_message = 'Logline created successfully.'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LoglineUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Logline
    fields = ['title', 'body']
    success_message = 'Logline updated successfully.'


class LoglineHistoryDetailView(DetailView):
    template_name = 'loglines/logline_detail_history.html'

    def get_object(self, queryset=None):
        return Logline.history.get(id=self.kwargs['pk'], history_id=self.kwargs['history_pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['index'] = Logline.history.filter(history_date__lt=self.object.history_date).count() + 1
        context['diff'] = self.get_diff()
        return context

    def get_diff(self):
        obj = self.get_object()
        if obj.prev_record is not None:
            dmp = PrettyDiffMatchPatch()
            diff = dmp.diff_main(obj.body, obj.prev_record.body)
            dmp.diff_cleanupSemantic(diff)
            return dmp.diff_prettyHtml(diff)
        else:
            return ''

lumberyard/templates/loglines/logline_detail.html
{% extends 'base.html' %}


{% block title %}{{ object.title }} &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'loglines:logline_list' %}">Loglines</a></li>
    <li class="breadcrumb-item active">{{ object.title }}</li>
</ol>

<h1>{{ object.title }}</h1>

<p><a href="{{ object.user.profile.get_absolute_url }}">{{ object.user.username }}</a></p>

<p><a href="{{ object.get_absolute_url }}">{{ object.updated }}</a></p>

<p>{{ object.body }}</p>

{% if user.is_authenticated and user == object.user %}
<p><a href="{% url 'loglines:logline_update' object.id %}">Update</a></p>
{% endif %}

{% if logline.history.all %}
<h2>Versions</h2>

<ol reversed>
    {% for obj in logline.history.all %}
    <li><a href="{% url 'loglines:logline_detail_history' obj.id obj.history_id %}">{{ obj.body }}</a></li>
    {% endfor %}
</ol>
{% endif %}

{% endblock %}

lumberyard/templates/loglines/logline_detail_history.html
{% extends 'base.html' %}


{% block title %}Version {{ index }} &#183; {{ object.title }} &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'loglines:logline_list' %}">Loglines</a></li>
    <li class="breadcrumb-item"><a href="{{ object.instance.get_absolute_url }}">{{ object.title }}</a></li>
    <li class="breadcrumb-item active">Version {{ index }}</li>
</ol>

<h1>{{ object.title }}</h1>

<p><a href="{{ object.user.profile.get_absolute_url }}">{{ object.user.username }}</a></p>

<p><a href="{% url 'loglines:logline_detail_history' object.id object.history_id %}">{{ object.created }}</a></p>

<p>{{ object.body }}</p>

{% if diff %}
<p>{{ diff|safe }}</p>
{% endif %}

{% if object.prev_record or object.next_record %}
<ul>
    {% if object.prev_record %}
    <li><a href="{% url 'loglines:logline_detail_history' object.id object.prev_record.history_id %}">&larr; {{ object.prev_record.created }}</a></li>
    {% endif %}
    {% if object.next_record %}
    <li><a href="{% url 'loglines:logline_detail_history' object.id object.next_record.history_id %}">{{ object.next_record.created }} &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

lumberyard/templates/loglines/logline_form.html
{% extends 'base.html' %}


{% block title %}{% if object %}Update {{ object.title }}{% else %}New logline{% endif %} &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'loglines:logline_list' %}">Loglines</a></li>
    {% if object %}
    <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></li>
    {% endif %}
    <li class="breadcrumb-item active">{% if object %}Update{% else %}New logline{% endif %}</li>
</ol>

<h1>{% if object %}{{ object.title }}{% else %}New logline{% endif %}</h1>

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% if object %}{% url 'loglines:logline_update' object.pk %}{% else %}{% url 'loglines:logline_create' %}{% endif %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if object %}Update{% else %}Create{% endif %} logline</button>
</form>

{% endblock %}

lumberyard/templates/loglines/logline_list.html
{% extends 'base.html' %}


{% block title %}Loglines &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item active">Loglines</li>
</ol>

<h1>Loglines</h1>

<p><a href="{% url 'loglines:logline_create' %}">New logline</a></p>

<ul>
    {% for obj in object_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}