lumberyard/accounts/urls.py
from django.urls import path

from .views import (
    AccountView,
    LoginView,
    LogoutView,
    PasswordView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    RegisterView,
)


app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('password/', PasswordView.as_view(), name='password'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AccountView.as_view(), name='account'),
]

lumberyard/loglines/urls.py
from django.urls import path

from .views import (
    LoglineCreateView,
    LoglineDetailView,
    LoglineListView,
    LoglineUpdateView,
    LoglineHistoryDetailView
)


app_name = 'loglines'

urlpatterns = [
    path('new/', LoglineCreateView.as_view(), name='logline_create'),
    path('<int:pk>/history/<int:history_pk>/', LoglineHistoryDetailView.as_view(), name='logline_detail_history'),
    path('<int:pk>/update/', LoglineUpdateView.as_view(), name='logline_update'),
    path('<int:pk>/', LoglineDetailView.as_view(), name='logline_detail'),
    path('', LoglineListView.as_view(), name='logline_list'),
]

lumberyard/lumberyard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('loglines/', include('loglines.urls')),
    path('', include('profiles.urls')),
    path('', HomeView.as_view(), name='home'),
]


if getattr(settings, 'DEBUG', False):
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lumberyard/profiles/urls.py
from django.urls import path

from .views import ProfileDetailView, ProfileListView


app_name = 'profiles'

urlpatterns = [
    path('writers/', ProfileListView.as_view(), name='profile_list'),
    path('<slug:username>/', ProfileDetailView.as_view(), name='profile_detail'),
]

lumberyard/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en-us" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{{ request.site.name }}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}?">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="{{ request.site.name }} is where you write a logline with instant feedback.">
    </head>
    <body>
        <header>
            <div><a href="{% url 'home' %}">{{ request.site.name }}</a></div>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'loglines:logline_list' %}">Loglines</a></li>
                <li><a href="{% url 'profiles:profile_list' %}">Writers</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'profiles:profile_detail' user.username %}">Profile</a></li>
                    <li><a href="{% url 'accounts:account' %}">Account</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </nav>
        <main>
            {% include 'includes/messages.html' %}
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <small>&copy; {% now 'Y' %} {{ request.site.name }}.</small>
        </footer>
    </body>
</html>

lumberyard/templates/home.html
{% extends 'base.html' %}


{% block content %}

<h1>Write a <del class="text-danger">screenplay</del> <span class="text-success">logline</span>.</h1>

<p><strong>{{ request.site.name }}</strong> is where you write loglines with instant feedback.</p>

<p><a href="{% url 'loglines:logline_create' %}">Write your first logline</a></p>

{% if logline_list %}
<p>Some loglines:</p>
<ul>
    {% for l in logline_list %}
    <li><a href="{{ l.get_absolute_url }}">{{ l.title }}</a></li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}