lumberyard/accounts/urls.py
from django.urls import path

from .views import (
    AccountView,
    LoginView,
    LogoutView,
    PasswordView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    RegisterView,
)


app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('password/', PasswordView.as_view(), name='password'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AccountView.as_view(), name='account'),
]

lumberyard/loglines/urls.py
from django.urls import path

from .views import (
    LoglineCreateView,
    LoglineDetailView,
    LoglineListView,
    LoglineUpdateView,
    LoglineHistoryDetailView
)


app_name = 'loglines'

urlpatterns = [
    path('new/', LoglineCreateView.as_view(), name='logline_create'),
    path('<int:pk>/history/<int:history_pk>/', LoglineHistoryDetailView.as_view(), name='logline_detail_history'),
    path('<int:pk>/update/', LoglineUpdateView.as_view(), name='logline_update'),
    path('<int:pk>/', LoglineDetailView.as_view(), name='logline_detail'),
    path('', LoglineListView.as_view(), name='logline_list'),
]

lumberyard/lumberyard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('loglines/', include('loglines.urls')),
    path('', include('profiles.urls')),
    path('', HomeView.as_view(), name='home'),
]


if getattr(settings, 'DEBUG', False):
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lumberyard/accounts/models.py
from django.contrib.auth.models import AbstractUser

from .validators import SlugASCIIUsernameValidator


class User(AbstractUser):
    username_validator = SlugASCIIUsernameValidator()

lumberyard/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()


class RegisterForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            User.USERNAME_FIELD,
            User.get_email_field_name(),
            'password',
        ]
        labels = {
            User.get_email_field_name(): 'Email',
        }
        help_texts = {
            User.USERNAME_FIELD: '',
        }
        widgets = {
            User.USERNAME_FIELD: forms.TextInput(attrs={
                'autocapitalize': 'off',
                'autocomplete': 'username',
                'autocorrect': 'off',
                'autofocus': True,
                'class': 'form-control form-control-lg',
            }),
            User.get_email_field_name(): forms.EmailInput(attrs={
                'autocapitalize': 'off',
                'autocomplete': 'home email',
                'autocorrect': 'off',
                'class': 'form-control form-control-lg',
            }),
            'password': forms.PasswordInput(attrs={
                'autocapitalize': 'off',
                'autocomplete': 'new-password',
                'autocorrect': 'off',
                'class': 'form-control form-control-lg',
            }),
        }

    def clean_username(self):
        username = self.cleaned_data[User.USERNAME_FIELD]
        return username.lower()

    def clean_email(self):
        email_field = User.get_email_field_name()
        email = self.cleaned_data[email_field]
        if User.objects.filter(email=email).exists():
            raise ValidationError('A user with that e-mail already exists.')
        return email.lower()

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

lumberyard/accounts/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetConfirmView, PasswordResetView, PasswordResetDoneView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from .forms import RegisterForm
from loglines.models import Logline

User = get_user_model()


class AccountView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['logline_list'] = Logline.objects.filter(user=self.request.user)
        return context


class PasswordView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    form_class = SetPasswordForm
    success_message = 'Password changed successfully.'
    template_name = 'accounts/password_form.html'
    success_url = reverse_lazy('accounts:password')


class LoginView(SuccessMessageMixin, LoginView):
    success_message = 'Logged in successfully.'
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('accounts:account')
        return super().dispatch(request, *args, **kwargs)


class LogoutView(LoginRequiredMixin, SuccessMessageMixin, LogoutView):
    pass


class RegisterView(FormView):
    template_name = 'accounts/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:account')

    def form_valid(self, form):
        obj = form.save()
        obj = authenticate(**{
            User.USERNAME_FIELD: obj.get_username(),
            'password': form.cleaned_data['password']
        })
        login(self.request, obj)
        return super().form_valid(form)


class PasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    post_reset_login = True
    success_message = 'Password reset successfully.'
    success_url = reverse_lazy('accounts:account')
    template_name = 'accounts/password_reset_confirm.html'

lumberyard/templates/accounts/account.html
{% extends 'base.html' %}


{% block title %}Account &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Account</h1>

<ul>
    <li><a href="{% url 'accounts:password' %}">Password</a></li>
</ul>

{% if logline_list %}
<h2>Loglines</h2>
<ul>
    {% for obj in logline_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No loglines.</p>
<p><a href="{% url 'loglines:logline_create' %}">Write your first logline</a></p>
{% endif %}

{% endblock %}

lumberyard/templates/accounts/login.html
{% extends 'base.html' %}


{% block title %}Login &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Login</h1>

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
    {% else %}
    <p>Please log in to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit">Log in</button>
</form>

<p><a href="{% url 'accounts:password_reset' %}">Lost password?</a></p>

<p><a href="{% url 'accounts:register' %}">Register</a></p>

{% endblock %}

lumberyard/templates/accounts/password_form.html
{% extends 'base.html' %}


{% block title %}Password &#183; Account &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Account</a></li>
    <li class="breadcrumb-item">Password</li>
</ol>

<h1>Account</h1>

<h2>Password</h2>

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% url 'accounts:password' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change password</button>
</form>

<ul>
    <li><a href="{% url 'accounts:password' %}">Password</a></li>
</ul>

{% endblock %}

lumberyard/templates/accounts/password_reset.html
{% extends 'base.html' %}


{% block title %}Password reset &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Password reset</h1>

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% url 'accounts:password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
</form>

{% endblock %}

lumberyard/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}


{% block title %}Password reset &#183; Account &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Password reset</h1>

{% if validlink %}

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
</form>

{% else %}

<p>Please try <a href="{% url 'accounts:password_reset' %}">resetting your password again</a>.</p>

{% endif %}

{% endblock %}

lumberyard/templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block title %}Password reset &#183; Account &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Password reset</h1>

<p>Check your inbox.</p>

{% endblock %}

lumberyard/templates/accounts/password_reset_email.html
{% autoescape off %}Hello,

You're receiving this email because someone requested a password reset for the account {{ user.get_username }} at {{ site_name }}. Visit the link to reset your password.

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

{{ site_name }}{% endautoescape %}

lumberyard/templates/accounts/register.html
{% extends 'base.html' %}


{% block title %}Register &#183; {{ block.super }}{% endblock %}


{% block content %}

<h1>Register</h1>

{% if form.non_field_errors %}
<ul>
    {% for error in form.non_field_errors %}
    <li>{{ error|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

<p><a href="{% url 'accounts:login' %}">Login</a></p>

{% endblock %}