lumberyard/accounts/urls.py
from django.urls import path

from .views import (
    AccountView,
    LoginView,
    LogoutView,
    PasswordView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    RegisterView,
)


app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('password/', PasswordView.as_view(), name='password'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AccountView.as_view(), name='account'),
]

lumberyard/loglines/urls.py
from django.urls import path

from .views import (
    LoglineCreateView,
    LoglineDetailView,
    LoglineListView,
    LoglineUpdateView,
    LoglineHistoryDetailView
)


app_name = 'loglines'

urlpatterns = [
    path('new/', LoglineCreateView.as_view(), name='logline_create'),
    path('<int:pk>/history/<int:history_pk>/', LoglineHistoryDetailView.as_view(), name='logline_detail_history'),
    path('<int:pk>/update/', LoglineUpdateView.as_view(), name='logline_update'),
    path('<int:pk>/', LoglineDetailView.as_view(), name='logline_detail'),
    path('', LoglineListView.as_view(), name='logline_list'),
]

lumberyard/lumberyard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('loglines/', include('loglines.urls')),
    path('', include('profiles.urls')),
    path('', HomeView.as_view(), name='home'),
]


if getattr(settings, 'DEBUG', False):
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lumberyard/profiles/urls.py
from django.urls import path

from .views import ProfileDetailView, ProfileListView


app_name = 'profiles'

urlpatterns = [
    path('writers/', ProfileListView.as_view(), name='profile_list'),
    path('<slug:username>/', ProfileDetailView.as_view(), name='profile_detail'),
]

lumberyard/loglines/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from simple_history.models import HistoricalRecords


class Logline(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('loglines:logline_detail', args=[str(self.pk)])

lumberyard/profiles/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['user__%s' % User.USERNAME_FIELD]

    def __str__(self):
        return self.user.get_username()

    def get_absolute_url(self):
        return reverse('profiles:profile_detail', args=[self.user.get_username()])


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

lumberyard/profiles/views.py
from django.views.generic import DetailView, ListView

from .models import Profile


class ProfileListView(ListView):
    model = Profile


class ProfileDetailView(DetailView):
    model = Profile
    slug_field = 'user__username'
    slug_url_kwarg = 'username'

lumberyard/templates/profiles/profile_detail.html
{% extends 'base.html' %}


{% block title %}{{ object.user.username }} &#183; {{ block.super }}{% endblock %}

{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'profiles:profile_list' %}">Writers</a></li>
    <li class="breadcrumb-item active">{{ object.user.username }}</li>
</ol>

<h1>{{ object.user.username }}</h1>

{% if object.user.logline_set.all %}
<ul>
    {% for obj in object.user.logline_set.all %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No loglines.</p>
    {% if user.is_authenticated and user == object.user %}
    <p><a href="{% url 'loglines:logline_create' %}">Write your first logline</a></p>
    {% endif %}
{% endif %}

{% endblock %}

lumberyard/templates/profiles/profile_list.html
{% extends 'base.html' %}


{% block title %}Writers &#183; {{ block.super }}{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item active">Writers</li>
</ol>

<h1>Writers</h1>

<ul>
    {% for obj in object_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
    {% endfor %}
</ul>

{% endblock %}